### PR TITLE
Cleanup layout

### PR DESCRIPTION
**Pull request by sbinet**

### CODE REVIEW

**Comment by sbinet** [comment]
@rmadar PTAL

**Comment by rmadar** [comment]
Thanks, the things you changed are really cool features (tests, examples, and the literal value definition of a struct, as well as the `.String()` method).

**Comment by sbinet** [comment]
and look at your new "achievement unlocked" :)
https://godoc.org/github.com/rmadar/go-lorentz-vector/lv#pkg-examples

**Comment by rmadar** [comment]
This is **super nice**! Is it done automatically or ...? What if I change the structure of the package, or the code itself (or even the doc via the comments)? Also, where can I find the doc on the what is supported by the documentation syntax? Thanks!

**Comment by sbinet** [comment]
it's done automatically.
you can refresh it at the bottom of that page (`Refresh now`).

here is documentation about how to write documentation (and other "writing Go code" aspects):
- https://golang.org/doc/effective_go.html#commentary
- https://blog.golang.org/godoc
- https://blog.golang.org/organizing-go-code
- https://blog.golang.org/gofmt
- https://blog.golang.org/package-names
- https://blog.golang.org/examples

**Comment by rmadar** [comment]
Why some repository have an automatically created documentation and not other? I checked `github.com/rmadar/go-simple-examples` and it is not existing. Thanks.

**Comment by sbinet** [comment]
`godoc` will display documentation for repositories (and (sub)directories) that contain Go files (`*.go`).

for top-level documentation (ie: that of a package or command), one needs to add some comment just above the `package` directive:

```go
// Package foo provides very useful functions to bar stuff.
package foo
```

```go
// Command root-ls inspects the content of ROOT files
package main
```

**Pull request merged**
